variable "region_name" {}
variable "Vpc_cidr_block" {}
variable "vpc_tag" {}
variable "subnet_cidr_block" {}
variable "subnet_az" {}
variable "subnet_tag" {}
variable "igw_tag" {}
variable "rt_cidr_block" {}
variable "rt_tag" {}
variable "ec2_az" {}
variable "instance_type" {}
variable "key_name" {}
